package br.com.rabelo.smartserver.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcfCaixa generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_caixa", catalog = "retaguarda")
public class EcfCaixa extends GenericDomain {
	@Column(name = "NOME", length = 30)
	private String nome;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_CADASTRO", length = 10)
	private Date dataCadastro;

	@Column(name = "HASH_TRIPA", length = 32)
	private String hashTripa;

	@Column(name = "HASH_INCREMENTO")
	private Integer hashIncremento;

	public EcfCaixa() {
	}

	public EcfCaixa(String nome, Date dataCadastro, String hashTripa, Integer hashIncremento) {
		this.nome = nome;
		this.dataCadastro = dataCadastro;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Date getDataCadastro() {
		return dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public String getHashTripa() {
		return hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	public Integer getHashIncremento() {
		return hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}
}
