package br.com.rabelo.smartserver.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcfConfiguracao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_configuracao", catalog = "retaguarda")
public class EcfConfiguracao extends GenericDomain {
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_CAIXA", nullable = false)
	private EcfCaixa ecfCaixa;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_EMPRESA", nullable = false)
	private EcfEmpresa ecfEmpresa;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_IMPRESSORA", nullable = false)
	private EcfImpressora ecfImpressora;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_RESOLUCAO", nullable = false)
	private EcfResolucao ecfResolucao;

	@Column(name = "NOME_CAIXA", length = 30)
	private String nomeCaixa;

	@Column(name = "ID_GERADO_CAIXA")
	private Integer idGeradoCaixa;

	@Column(name = "ID_EMPRESA")
	private Integer idEmpresa;

	@Column(name = "MENSAGEM_CUPOM", length = 250)
	private String mensagemCupom;

	@Column(name = "PORTA_ECF", length = 10)
	private Character portaEcf;

	@Column(name = "PORTA_PINPAD", length = 10)
	private Character portaPinpad;

	@Column(name = "PORTA_BALANCA", length = 10)
	private Character portaBalanca;

	@Column(name = "IP_SERVIDOR", length = 15)
	private String ipServidor;

	@Column(name = "IP_SITEF", length = 15)
	private String ipSitef;

	@Column(name = "TIPO_TEF", length = 15)
	private String tipoTef;

	@Column(name = "TITULO_TELA_CAIXA", length = 100)
	private String tituloTelaCaixa;

	@Column(name = "CAMINHO_IMAGENS_PRODUTOS", length = 250)
	private String caminhoImagensProdutos;

	@Column(name = "CAMINHO_IMAGENS_MARKETING", length = 250)
	private String caminhoImagensMarketing;

	@Column(name = "CAMINHO_IMAGENS_LAYOUT", length = 250)
	private String caminhoImagensLayout;

	@Column(name = "COR_JANELAS_INTERNAS", length = 20)
	private String corJanelasInternas;

	@Column(name = "MARKETING_ATIVO", length = 1)
	private Character marketingAtivo;

	@Column(name = "CFOP_ECF")
	private Integer cfopEcf;

	@Column(name = "CFOP_NF2")
	private Integer cfopNf2;

	@Column(name = "TIMEOUT_ECF")
	private Integer timeoutEcf;

	@Column(name = "INTERVALO_ECF")
	private Integer intervaloEcf;

	@Column(name = "DESCRICAO_SUPRIMENTO", length = 20)
	private String descricaoSuprimento;

	@Column(name = "DESCRICAO_SANGRIA", length = 20)
	private String descricaoSangria;

	@Column(name = "TEF_CODIGO_LOJA", length = 15)
	private String tefCodigoLoja;

	@Column(name = "TEF_CODIGO_TERMINAL", length = 15)
	private String tefCodigoTerminal;

	@Column(name = "TEF_TIPO_GP")
	private Integer tefTipoGp;

	@Column(name = "TEF_TEMPO_ESPERA")
	private Integer tefTempoEspera;

	@Column(name = "TEF_ESPERA_STS")
	private Integer tefEsperaSts;

	@Column(name = "TEF_NUMERO_VIAS")
	private Integer tefNumeroVias;

	@Column(name = "INDICE_GERENCIAL_DAV")
	private Integer indiceGerencialDav;

	@Column(name = "DECIMAIS_QUANTIDADE")
	private Integer decimaisQuantidade;

	@Column(name = "DECIMAIS_VALOR")
	private Integer decimaisValor;

	@Column(name = "BITS_POR_SEGUNDO")
	private Integer bitsPorSegundo;

	@Column(name = "QTDE_MAXIMA_CARTOES")
	private Integer qtdeMaximaCartoes;

	@Column(name = "PESQUISA_PARTE", length = 1)
	private Character pesquisaParte;

	@Column(name = "CONFIGURACAO_BALANCA", length = 100)
	private String configuracaoBalanca;

	@Column(name = "PARAMETROS_DIVERSOS", length = 250)
	private String parametrosDiversos;

	@Column(name = "ULTIMA_EXCLUSAO")
	private Integer ultimaExclusao;

	@Column(name = "INDICE_GERENCIAL_IDENTIFICA")
	private Integer indiceGerencialIdentifica;

	@Column(name = "LAUDO", length = 10)
	private String laudo;

	@Column(name = "INDICE_GERENCIAL", length = 100)
	private String indiceGerencial;

	@Column(name = "ID_CNF_RECARGA_CELULAR")
	private Integer idCnfRecargaCelular;

	@Column(name = "ID_CNF_RECEBIMENTO")
	private Integer idCnfRecebimento;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_ATUALIZACAO_ESTOQUE", length = 10)
	private Date dataAtualizacaoEstoque;

	@Column(name = "SINCRONIZADO", length = 1)
	private Character sincronizado;

	@Column(name = "HORA_ATUALIZACAO_ESTOQUE", length = 8)
	private String horaAtualizacaoEstoque;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_SINCRONIZACAO", length = 10)
	private Date dataSincronizacao;

	@Column(name = "HORA_SINCRONIZACAO", length = 8)
	private String horaSincronizacao;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_HORA_ATUAL_PRODUTO", length = 19)
	private Date dataHoraAtualProduto;

	@Column(name = "HASH_TRIPA", length = 32)
	private String hashTripa;

	@Column(name = "HASH_INCREMENTO")
	private Integer hashIncremento;

	@Column(name = "PAF_REL_PARAM_CONFIG", length = 10)
	private String pafRelParamConfig;

	@Column(name = "PERMITE_VENDA_DIRETA", length = 1)
	private String permiteVendaDireta;

	public EcfConfiguracao() {
	}

	public EcfConfiguracao(EcfCaixa ecfCaixa, EcfEmpresa ecfEmpresa, EcfImpressora ecfImpressora,
			EcfResolucao ecfResolucao) {
		this.ecfCaixa = ecfCaixa;
		this.ecfEmpresa = ecfEmpresa;
		this.ecfImpressora = ecfImpressora;
		this.ecfResolucao = ecfResolucao;
	}

	public EcfConfiguracao(EcfCaixa ecfCaixa, EcfEmpresa ecfEmpresa, EcfImpressora ecfImpressora,
			EcfResolucao ecfResolucao, String nomeCaixa, Integer idGeradoCaixa, Integer idEmpresa, String mensagemCupom,
			Character portaEcf, Character portaPinpad, Character portaBalanca, String ipServidor, String ipSitef,
			String tipoTef, String tituloTelaCaixa, String caminhoImagensProdutos, String caminhoImagensMarketing,
			String caminhoImagensLayout, String corJanelasInternas, Character marketingAtivo, Integer cfopEcf,
			Integer cfopNf2, Integer timeoutEcf, Integer intervaloEcf, String descricaoSuprimento,
			String descricaoSangria, String tefCodigoLoja, String tefCodigoTerminal, Integer tefTipoGp,
			Integer tefTempoEspera, Integer tefEsperaSts, Integer tefNumeroVias, Integer indiceGerencialDav,
			Integer decimaisQuantidade, Integer decimaisValor, Integer bitsPorSegundo, Integer qtdeMaximaCartoes,
			Character pesquisaParte, String configuracaoBalanca, String parametrosDiversos, Integer ultimaExclusao,
			Integer indiceGerencialIdentifica, String laudo, String indiceGerencial, Integer idCnfRecargaCelular,
			Integer idCnfRecebimento, Date dataAtualizacaoEstoque, Character sincronizado,
			String horaAtualizacaoEstoque, Date dataSincronizacao, String horaSincronizacao, Date dataHoraAtualProduto,
			String hashTripa, Integer hashIncremento, String pafRelParamConfig, String permiteVendaDireta) {
		this.ecfCaixa = ecfCaixa;
		this.ecfEmpresa = ecfEmpresa;
		this.ecfImpressora = ecfImpressora;
		this.ecfResolucao = ecfResolucao;
		this.nomeCaixa = nomeCaixa;
		this.idGeradoCaixa = idGeradoCaixa;
		this.idEmpresa = idEmpresa;
		this.mensagemCupom = mensagemCupom;
		this.portaEcf = portaEcf;
		this.portaPinpad = portaPinpad;
		this.portaBalanca = portaBalanca;
		this.ipServidor = ipServidor;
		this.ipSitef = ipSitef;
		this.tipoTef = tipoTef;
		this.tituloTelaCaixa = tituloTelaCaixa;
		this.caminhoImagensProdutos = caminhoImagensProdutos;
		this.caminhoImagensMarketing = caminhoImagensMarketing;
		this.caminhoImagensLayout = caminhoImagensLayout;
		this.corJanelasInternas = corJanelasInternas;
		this.marketingAtivo = marketingAtivo;
		this.cfopEcf = cfopEcf;
		this.cfopNf2 = cfopNf2;
		this.timeoutEcf = timeoutEcf;
		this.intervaloEcf = intervaloEcf;
		this.descricaoSuprimento = descricaoSuprimento;
		this.descricaoSangria = descricaoSangria;
		this.tefCodigoLoja = tefCodigoLoja;
		this.tefCodigoTerminal = tefCodigoTerminal;
		this.tefTipoGp = tefTipoGp;
		this.tefTempoEspera = tefTempoEspera;
		this.tefEsperaSts = tefEsperaSts;
		this.tefNumeroVias = tefNumeroVias;
		this.indiceGerencialDav = indiceGerencialDav;
		this.decimaisQuantidade = decimaisQuantidade;
		this.decimaisValor = decimaisValor;
		this.bitsPorSegundo = bitsPorSegundo;
		this.qtdeMaximaCartoes = qtdeMaximaCartoes;
		this.pesquisaParte = pesquisaParte;
		this.configuracaoBalanca = configuracaoBalanca;
		this.parametrosDiversos = parametrosDiversos;
		this.ultimaExclusao = ultimaExclusao;
		this.indiceGerencialIdentifica = indiceGerencialIdentifica;
		this.laudo = laudo;
		this.indiceGerencial = indiceGerencial;
		this.idCnfRecargaCelular = idCnfRecargaCelular;
		this.idCnfRecebimento = idCnfRecebimento;
		this.dataAtualizacaoEstoque = dataAtualizacaoEstoque;
		this.sincronizado = sincronizado;
		this.horaAtualizacaoEstoque = horaAtualizacaoEstoque;
		this.dataSincronizacao = dataSincronizacao;
		this.horaSincronizacao = horaSincronizacao;
		this.dataHoraAtualProduto = dataHoraAtualProduto;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
		this.pafRelParamConfig = pafRelParamConfig;
		this.permiteVendaDireta = permiteVendaDireta;
	}

	public EcfCaixa getEcfCaixa() {
		return this.ecfCaixa;
	}

	public void setEcfCaixa(EcfCaixa ecfCaixa) {
		this.ecfCaixa = ecfCaixa;
	}

	public EcfEmpresa getEcfEmpresa() {
		return this.ecfEmpresa;
	}

	public void setEcfEmpresa(EcfEmpresa ecfEmpresa) {
		this.ecfEmpresa = ecfEmpresa;
	}

	public EcfImpressora getEcfImpressora() {
		return this.ecfImpressora;
	}

	public void setEcfImpressora(EcfImpressora ecfImpressora) {
		this.ecfImpressora = ecfImpressora;
	}

	public EcfResolucao getEcfResolucao() {
		return this.ecfResolucao;
	}

	public void setEcfResolucao(EcfResolucao ecfResolucao) {
		this.ecfResolucao = ecfResolucao;
	}

	public String getNomeCaixa() {
		return this.nomeCaixa;
	}

	public void setNomeCaixa(String nomeCaixa) {
		this.nomeCaixa = nomeCaixa;
	}

	public Integer getIdGeradoCaixa() {
		return this.idGeradoCaixa;
	}

	public void setIdGeradoCaixa(Integer idGeradoCaixa) {
		this.idGeradoCaixa = idGeradoCaixa;
	}

	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getMensagemCupom() {
		return this.mensagemCupom;
	}

	public void setMensagemCupom(String mensagemCupom) {
		this.mensagemCupom = mensagemCupom;
	}

	public Character getPortaEcf() {
		return this.portaEcf;
	}

	public void setPortaEcf(Character portaEcf) {
		this.portaEcf = portaEcf;
	}

	public Character getPortaPinpad() {
		return this.portaPinpad;
	}

	public void setPortaPinpad(Character portaPinpad) {
		this.portaPinpad = portaPinpad;
	}

	public Character getPortaBalanca() {
		return this.portaBalanca;
	}

	public void setPortaBalanca(Character portaBalanca) {
		this.portaBalanca = portaBalanca;
	}

	public String getIpServidor() {
		return this.ipServidor;
	}

	public void setIpServidor(String ipServidor) {
		this.ipServidor = ipServidor;
	}

	public String getIpSitef() {
		return this.ipSitef;
	}

	public void setIpSitef(String ipSitef) {
		this.ipSitef = ipSitef;
	}

	public String getTipoTef() {
		return this.tipoTef;
	}

	public void setTipoTef(String tipoTef) {
		this.tipoTef = tipoTef;
	}

	public String getTituloTelaCaixa() {
		return this.tituloTelaCaixa;
	}

	public void setTituloTelaCaixa(String tituloTelaCaixa) {
		this.tituloTelaCaixa = tituloTelaCaixa;
	}

	public String getCaminhoImagensProdutos() {
		return this.caminhoImagensProdutos;
	}

	public void setCaminhoImagensProdutos(String caminhoImagensProdutos) {
		this.caminhoImagensProdutos = caminhoImagensProdutos;
	}

	public String getCaminhoImagensMarketing() {
		return this.caminhoImagensMarketing;
	}

	public void setCaminhoImagensMarketing(String caminhoImagensMarketing) {
		this.caminhoImagensMarketing = caminhoImagensMarketing;
	}

	public String getCaminhoImagensLayout() {
		return this.caminhoImagensLayout;
	}

	public void setCaminhoImagensLayout(String caminhoImagensLayout) {
		this.caminhoImagensLayout = caminhoImagensLayout;
	}

	public String getCorJanelasInternas() {
		return this.corJanelasInternas;
	}

	public void setCorJanelasInternas(String corJanelasInternas) {
		this.corJanelasInternas = corJanelasInternas;
	}

	public Character getMarketingAtivo() {
		return this.marketingAtivo;
	}

	public void setMarketingAtivo(Character marketingAtivo) {
		this.marketingAtivo = marketingAtivo;
	}

	public Integer getCfopEcf() {
		return this.cfopEcf;
	}

	public void setCfopEcf(Integer cfopEcf) {
		this.cfopEcf = cfopEcf;
	}

	public Integer getCfopNf2() {
		return this.cfopNf2;
	}

	public void setCfopNf2(Integer cfopNf2) {
		this.cfopNf2 = cfopNf2;
	}

	public Integer getTimeoutEcf() {
		return this.timeoutEcf;
	}

	public void setTimeoutEcf(Integer timeoutEcf) {
		this.timeoutEcf = timeoutEcf;
	}

	public Integer getIntervaloEcf() {
		return this.intervaloEcf;
	}

	public void setIntervaloEcf(Integer intervaloEcf) {
		this.intervaloEcf = intervaloEcf;
	}

	public String getDescricaoSuprimento() {
		return this.descricaoSuprimento;
	}

	public void setDescricaoSuprimento(String descricaoSuprimento) {
		this.descricaoSuprimento = descricaoSuprimento;
	}

	public String getDescricaoSangria() {
		return this.descricaoSangria;
	}

	public void setDescricaoSangria(String descricaoSangria) {
		this.descricaoSangria = descricaoSangria;
	}

	public String getTefCodigoLoja() {
		return this.tefCodigoLoja;
	}

	public void setTefCodigoLoja(String tefCodigoLoja) {
		this.tefCodigoLoja = tefCodigoLoja;
	}

	public String getTefCodigoTerminal() {
		return this.tefCodigoTerminal;
	}

	public void setTefCodigoTerminal(String tefCodigoTerminal) {
		this.tefCodigoTerminal = tefCodigoTerminal;
	}

	public Integer getTefTipoGp() {
		return this.tefTipoGp;
	}

	public void setTefTipoGp(Integer tefTipoGp) {
		this.tefTipoGp = tefTipoGp;
	}

	public Integer getTefTempoEspera() {
		return this.tefTempoEspera;
	}

	public void setTefTempoEspera(Integer tefTempoEspera) {
		this.tefTempoEspera = tefTempoEspera;
	}

	public Integer getTefEsperaSts() {
		return this.tefEsperaSts;
	}

	public void setTefEsperaSts(Integer tefEsperaSts) {
		this.tefEsperaSts = tefEsperaSts;
	}

	public Integer getTefNumeroVias() {
		return this.tefNumeroVias;
	}

	public void setTefNumeroVias(Integer tefNumeroVias) {
		this.tefNumeroVias = tefNumeroVias;
	}

	public Integer getIndiceGerencialDav() {
		return this.indiceGerencialDav;
	}

	public void setIndiceGerencialDav(Integer indiceGerencialDav) {
		this.indiceGerencialDav = indiceGerencialDav;
	}

	public Integer getDecimaisQuantidade() {
		return this.decimaisQuantidade;
	}

	public void setDecimaisQuantidade(Integer decimaisQuantidade) {
		this.decimaisQuantidade = decimaisQuantidade;
	}

	public Integer getDecimaisValor() {
		return this.decimaisValor;
	}

	public void setDecimaisValor(Integer decimaisValor) {
		this.decimaisValor = decimaisValor;
	}

	public Integer getBitsPorSegundo() {
		return this.bitsPorSegundo;
	}

	public void setBitsPorSegundo(Integer bitsPorSegundo) {
		this.bitsPorSegundo = bitsPorSegundo;
	}

	public Integer getQtdeMaximaCartoes() {
		return this.qtdeMaximaCartoes;
	}

	public void setQtdeMaximaCartoes(Integer qtdeMaximaCartoes) {
		this.qtdeMaximaCartoes = qtdeMaximaCartoes;
	}

	public Character getPesquisaParte() {
		return this.pesquisaParte;
	}

	public void setPesquisaParte(Character pesquisaParte) {
		this.pesquisaParte = pesquisaParte;
	}

	public String getConfiguracaoBalanca() {
		return this.configuracaoBalanca;
	}

	public void setConfiguracaoBalanca(String configuracaoBalanca) {
		this.configuracaoBalanca = configuracaoBalanca;
	}

	public String getParametrosDiversos() {
		return this.parametrosDiversos;
	}

	public void setParametrosDiversos(String parametrosDiversos) {
		this.parametrosDiversos = parametrosDiversos;
	}

	public Integer getUltimaExclusao() {
		return this.ultimaExclusao;
	}

	public void setUltimaExclusao(Integer ultimaExclusao) {
		this.ultimaExclusao = ultimaExclusao;
	}

	public Integer getIndiceGerencialIdentifica() {
		return this.indiceGerencialIdentifica;
	}

	public void setIndiceGerencialIdentifica(Integer indiceGerencialIdentifica) {
		this.indiceGerencialIdentifica = indiceGerencialIdentifica;
	}

	public String getLaudo() {
		return this.laudo;
	}

	public void setLaudo(String laudo) {
		this.laudo = laudo;
	}

	public String getIndiceGerencial() {
		return this.indiceGerencial;
	}

	public void setIndiceGerencial(String indiceGerencial) {
		this.indiceGerencial = indiceGerencial;
	}

	public Integer getIdCnfRecargaCelular() {
		return this.idCnfRecargaCelular;
	}

	public void setIdCnfRecargaCelular(Integer idCnfRecargaCelular) {
		this.idCnfRecargaCelular = idCnfRecargaCelular;
	}

	public Integer getIdCnfRecebimento() {
		return this.idCnfRecebimento;
	}

	public void setIdCnfRecebimento(Integer idCnfRecebimento) {
		this.idCnfRecebimento = idCnfRecebimento;
	}

	public Date getDataAtualizacaoEstoque() {
		return this.dataAtualizacaoEstoque;
	}

	public void setDataAtualizacaoEstoque(Date dataAtualizacaoEstoque) {
		this.dataAtualizacaoEstoque = dataAtualizacaoEstoque;
	}

	public Character getSincronizado() {
		return this.sincronizado;
	}

	public void setSincronizado(Character sincronizado) {
		this.sincronizado = sincronizado;
	}

	public String getHoraAtualizacaoEstoque() {
		return this.horaAtualizacaoEstoque;
	}

	public void setHoraAtualizacaoEstoque(String horaAtualizacaoEstoque) {
		this.horaAtualizacaoEstoque = horaAtualizacaoEstoque;
	}

	public Date getDataSincronizacao() {
		return this.dataSincronizacao;
	}

	public void setDataSincronizacao(Date dataSincronizacao) {
		this.dataSincronizacao = dataSincronizacao;
	}

	public String getHoraSincronizacao() {
		return this.horaSincronizacao;
	}

	public void setHoraSincronizacao(String horaSincronizacao) {
		this.horaSincronizacao = horaSincronizacao;
	}

	public Date getDataHoraAtualProduto() {
		return this.dataHoraAtualProduto;
	}

	public void setDataHoraAtualProduto(Date dataHoraAtualProduto) {
		this.dataHoraAtualProduto = dataHoraAtualProduto;
	}

	public String getHashTripa() {
		return this.hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	public Integer getHashIncremento() {
		return this.hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}

	public String getPafRelParamConfig() {
		return this.pafRelParamConfig;
	}

	public void setPafRelParamConfig(String pafRelParamConfig) {
		this.pafRelParamConfig = pafRelParamConfig;
	}

	public String getPermiteVendaDireta() {
		return this.permiteVendaDireta;
	}

	public void setPermiteVendaDireta(String permiteVendaDireta) {
		this.permiteVendaDireta = permiteVendaDireta;
	}

}
