package br.com.rabelo.smartserver.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcfImpressora generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_impressora", catalog = "retaguarda")
public class EcfImpressora extends GenericDomain {
	@Column(name = "NUMERO")
	private Integer numero;

	@Column(name = "CODIGO", length = 10)
	private String codigo;

	@Column(name = "SERIE", length = 30)
	private String serie;

	@Column(name = "IDENTIFICACAO", length = 250)
	private String identificacao;
	
	@Column(name = "MC", length = 2)
	private Character mc;

	@Column(name = "MD", length = 2)
	private Character md;

	@Column(name = "VR", length = 2)
	private Character vr;

	@Column(name = "TIPO", length = 7)
	private String tipo;

	@Column(name = "MARCA", length = 30)
	private String marca;

	@Column(name = "MODELO", length = 30)
	private String modelo;

	@Column(name = "MODELO_ACBR", length = 30)
	private String modeloAcbr;

	@Column(name = "MODELO_DOCUMENTO_FISCAL", length = 2)
	private Character modeloDocumentoFiscal;

	@Column(name = "VERSAO", length = 30)
	private String versao;

	@Column(name = "LE", length = 1)
	private Character le;

	@Column(name = "LEF", length = 1)
	private Character lef;

	@Column(name = "MFD", length = 1)
	private Character mfd;

	@Column(name = "LACRE_NA_MFD", length = 1)
	private Character lacreNaMfd;

	@Column(name = "DOCTO", length = 60)
	private String docto;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_INSTALACAO_SB", length = 10)
	private Date dataInstalacaoSb;

	@Column(name = "HORA_INSTALACAO_SB", length = 8)
	private String horaInstalacaoSb;

	@Column(name = "ECF_IMPRESSORA", length = 3)
	private String ecfImpressora;

	@Column(name = "HASH_TRIPA", length = 32)
	private String hashTripa;

	@Column(name = "HASH_INCREMENTO")
	private Integer hashIncremento;

	/**
	 * private Set ecfMovimentos = new HashSet(0); private Set ecfConfiguracaos
	 * = new HashSet(0);
	 */

	public EcfImpressora() {
	}

	public EcfImpressora(Integer numero, String codigo, String serie, String identificacao, Character mc, Character md,
			Character vr, String tipo, String marca, String modelo, String modeloAcbr, Character modeloDocumentoFiscal,
			String versao, Character le, Character lef, Character mfd, Character lacreNaMfd, String docto,
			Date dataInstalacaoSb, String horaInstalacaoSb, String ecfImpressora, String hashTripa,
			Integer hashIncremento/**
									 * , Set ecfMovimentos, Set ecfConfiguracaos
									 */
	) {
		this.numero = numero;
		this.codigo = codigo;
		this.serie = serie;
		this.identificacao = identificacao;
		this.mc = mc;
		this.md = md;
		this.vr = vr;
		this.tipo = tipo;
		this.marca = marca;
		this.modelo = modelo;
		this.modeloAcbr = modeloAcbr;
		this.modeloDocumentoFiscal = modeloDocumentoFiscal;
		this.versao = versao;
		this.le = le;
		this.lef = lef;
		this.mfd = mfd;
		this.lacreNaMfd = lacreNaMfd;
		this.docto = docto;
		this.dataInstalacaoSb = dataInstalacaoSb;
		this.horaInstalacaoSb = horaInstalacaoSb;
		this.ecfImpressora = ecfImpressora;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
		/**
		 * this.ecfMovimentos = ecfMovimentos; this.ecfConfiguracaos =
		 * ecfConfiguracaos;
		 */
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public String getIdentificacao() {
		return this.identificacao;
	}

	public void setIdentificacao(String identificacao) {
		this.identificacao = identificacao;
	}

	public Character getMc() {
		return this.mc;
	}

	public void setMc(Character mc) {
		this.mc = mc;
	}

	public Character getMd() {
		return this.md;
	}

	public void setMd(Character md) {
		this.md = md;
	}

	public Character getVr() {
		return this.vr;
	}

	public void setVr(Character vr) {
		this.vr = vr;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getModeloAcbr() {
		return this.modeloAcbr;
	}

	public void setModeloAcbr(String modeloAcbr) {
		this.modeloAcbr = modeloAcbr;
	}

	public Character getModeloDocumentoFiscal() {
		return this.modeloDocumentoFiscal;
	}

	public void setModeloDocumentoFiscal(Character modeloDocumentoFiscal) {
		this.modeloDocumentoFiscal = modeloDocumentoFiscal;
	}

	public String getVersao() {
		return this.versao;
	}

	public void setVersao(String versao) {
		this.versao = versao;
	}

	public Character getLe() {
		return this.le;
	}

	public void setLe(Character le) {
		this.le = le;
	}

	public Character getLef() {
		return this.lef;
	}

	public void setLef(Character lef) {
		this.lef = lef;
	}

	public Character getMfd() {
		return this.mfd;
	}

	public void setMfd(Character mfd) {
		this.mfd = mfd;
	}

	public Character getLacreNaMfd() {
		return this.lacreNaMfd;
	}

	public void setLacreNaMfd(Character lacreNaMfd) {
		this.lacreNaMfd = lacreNaMfd;
	}

	public String getDocto() {
		return this.docto;
	}

	public void setDocto(String docto) {
		this.docto = docto;
	}

	public Date getDataInstalacaoSb() {
		return this.dataInstalacaoSb;
	}

	public void setDataInstalacaoSb(Date dataInstalacaoSb) {
		this.dataInstalacaoSb = dataInstalacaoSb;
	}

	public String getHoraInstalacaoSb() {
		return this.horaInstalacaoSb;
	}

	public void setHoraInstalacaoSb(String horaInstalacaoSb) {
		this.horaInstalacaoSb = horaInstalacaoSb;
	}

	public String getEcfImpressora() {
		return this.ecfImpressora;
	}

	public void setEcfImpressora(String ecfImpressora) {
		this.ecfImpressora = ecfImpressora;
	}

	public String getHashTripa() {
		return this.hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	public Integer getHashIncremento() {
		return this.hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}
	/**
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "ecfImpressora") public Set
	 *                  getEcfMovimentos() { return this.ecfMovimentos; }
	 * 
	 *                  public void setEcfMovimentos(Set ecfMovimentos) {
	 *                  this.ecfMovimentos = ecfMovimentos; }
	 * 
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "ecfImpressora") public Set
	 *                  getEcfConfiguracaos() { return this.ecfConfiguracaos; }
	 * 
	 *                  public void setEcfConfiguracaos(Set ecfConfiguracaos) {
	 *                  this.ecfConfiguracaos = ecfConfiguracaos; }
	 */
}
