package br.com.rabelo.smartserver.domain;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcfMovimento generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_movimento", catalog = "retaguarda")
public class EcfMovimento extends GenericDomain {
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_CAIXA", nullable = false)
	private EcfCaixa ecfCaixa;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_EMPRESA", nullable = false)
	private EcfEmpresa ecfEmpresa;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_IMPRESSORA", nullable = false)
	private EcfImpressora ecfImpressora;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_TURNO", nullable = false)
	private EcfTurno ecfTurno;

	@Column(name = "ID_ECF_OPERADOR", nullable = false)
	private int idEcfOperador;

	@Column(name = "NOME_CAIXA", length = 30)
	private String nomeCaixa;

	@Column(name = "ID_GERADO_CAIXA")
	private Integer idGeradoCaixa;

	@Column(name = "ID_GERENTE_SUPERVISOR", nullable = false)
	private int idGerenteSupervisor;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_ABERTURA", length = 10)
	private Date dataAbertura;

	@Column(name = "HORA_ABERTURA", length = 8)
	private String horaAbertura;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_FECHAMENTO", length = 10)
	private Date dataFechamento;

	@Column(name = "HORA_FECHAMENTO", length = 8)
	private String horaFechamento;

	@Column(name = "TOTAL_SUPRIMENTO", precision = 18, scale = 6)
	private BigDecimal totalSuprimento;

	@Column(name = "TOTAL_SANGRIA", precision = 18, scale = 6)
	private BigDecimal totalSangria;

	@Column(name = "TOTAL_NAO_FISCAL", precision = 18, scale = 6)
	private BigDecimal totalNaoFiscal;

	@Column(name = "TOTAL_VENDA", precision = 18, scale = 6)
	private BigDecimal totalVenda;

	@Column(name = "TOTAL_DESCONTO", precision = 18, scale = 6)
	private BigDecimal totalDesconto;

	@Column(name = "TOTAL_ACRESCIMO", precision = 18, scale = 6)
	private BigDecimal totalAcrescimo;

	@Column(name = "TOTAL_FINAL", precision = 18, scale = 6)
	private BigDecimal totalFinal;

	@Column(name = "TOTAL_RECEBIDO", precision = 18, scale = 6)
	private BigDecimal totalRecebido;

	@Column(name = "TOTAL_TROCO", precision = 18, scale = 6)
	private BigDecimal totalTroco;

	@Column(name = "TOTAL_CANCELADO", precision = 18, scale = 6)
	private BigDecimal totalCancelado;

	@Column(name = "STATUS_MOVIMENTO", nullable = false, length = 1)
	private char statusMovimento;

	@Column(name = "SINCRONIZADO", length = 1)
	private Character sincronizado;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_SINCRONIZACAO", length = 10)
	private Date dataSincronizacao;

	@Column(name = "HORA_SINCRONIZACAO", length = 8)
	private String horaSincronizacao;

	@Column(name = "HASH_TRIPA", length = 32)
	private String hashTripa;

	@Column(name = "HASH_INCREMENTO")
	private Integer hashIncremento;

	/**
	 * private Set ecfVendaCabecalhos = new HashSet(0); private Set
	 * ecfFechamentos = new HashSet(0); private Set ecfRecebimentoNaoFiscals =
	 * new HashSet(0);
	 */

	public EcfMovimento() {
	}

	public EcfMovimento(EcfCaixa ecfCaixa, EcfEmpresa ecfEmpresa, EcfImpressora ecfImpressora, EcfTurno ecfTurno,
			int idEcfOperador, int idGerenteSupervisor, char statusMovimento) {
		this.ecfCaixa = ecfCaixa;
		this.ecfEmpresa = ecfEmpresa;
		this.ecfImpressora = ecfImpressora;
		this.ecfTurno = ecfTurno;
		this.idEcfOperador = idEcfOperador;
		this.idGerenteSupervisor = idGerenteSupervisor;
		this.statusMovimento = statusMovimento;
	}

	public EcfMovimento(EcfCaixa ecfCaixa, EcfEmpresa ecfEmpresa, EcfImpressora ecfImpressora, EcfTurno ecfTurno,
			int idEcfOperador, String nomeCaixa, Integer idGeradoCaixa, int idGerenteSupervisor, Date dataAbertura,
			String horaAbertura, Date dataFechamento, String horaFechamento, BigDecimal totalSuprimento,
			BigDecimal totalSangria, BigDecimal totalNaoFiscal, BigDecimal totalVenda, BigDecimal totalDesconto,
			BigDecimal totalAcrescimo, BigDecimal totalFinal, BigDecimal totalRecebido, BigDecimal totalTroco,
			BigDecimal totalCancelado, char statusMovimento, Character sincronizado, Date dataSincronizacao,
			String horaSincronizacao, String hashTripa,
			Integer hashIncremento/**
									 * , Set ecfVendaCabecalhos, Set
									 * ecfFechamentos, Set
									 * ecfRecebimentoNaoFiscals
									 */
	) {
		this.ecfCaixa = ecfCaixa;
		this.ecfEmpresa = ecfEmpresa;
		this.ecfImpressora = ecfImpressora;
		this.ecfTurno = ecfTurno;
		this.idEcfOperador = idEcfOperador;
		this.nomeCaixa = nomeCaixa;
		this.idGeradoCaixa = idGeradoCaixa;
		this.idGerenteSupervisor = idGerenteSupervisor;
		this.dataAbertura = dataAbertura;
		this.horaAbertura = horaAbertura;
		this.dataFechamento = dataFechamento;
		this.horaFechamento = horaFechamento;
		this.totalSuprimento = totalSuprimento;
		this.totalSangria = totalSangria;
		this.totalNaoFiscal = totalNaoFiscal;
		this.totalVenda = totalVenda;
		this.totalDesconto = totalDesconto;
		this.totalAcrescimo = totalAcrescimo;
		this.totalFinal = totalFinal;
		this.totalRecebido = totalRecebido;
		this.totalTroco = totalTroco;
		this.totalCancelado = totalCancelado;
		this.statusMovimento = statusMovimento;
		this.sincronizado = sincronizado;
		this.dataSincronizacao = dataSincronizacao;
		this.horaSincronizacao = horaSincronizacao;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
		/**
		 * this.ecfVendaCabecalhos = ecfVendaCabecalhos; this.ecfFechamentos =
		 * ecfFechamentos; this.ecfRecebimentoNaoFiscals =
		 * ecfRecebimentoNaoFiscals;
		 */
	}

	public EcfCaixa getEcfCaixa() {
		return this.ecfCaixa;
	}

	public void setEcfCaixa(EcfCaixa ecfCaixa) {
		this.ecfCaixa = ecfCaixa;
	}

	public EcfEmpresa getEcfEmpresa() {
		return this.ecfEmpresa;
	}

	public void setEcfEmpresa(EcfEmpresa ecfEmpresa) {
		this.ecfEmpresa = ecfEmpresa;
	}

	public EcfImpressora getEcfImpressora() {
		return this.ecfImpressora;
	}

	public void setEcfImpressora(EcfImpressora ecfImpressora) {
		this.ecfImpressora = ecfImpressora;
	}

	public EcfTurno getEcfTurno() {
		return this.ecfTurno;
	}

	public void setEcfTurno(EcfTurno ecfTurno) {
		this.ecfTurno = ecfTurno;
	}

	public int getIdEcfOperador() {
		return this.idEcfOperador;
	}

	public void setIdEcfOperador(int idEcfOperador) {
		this.idEcfOperador = idEcfOperador;
	}

	public String getNomeCaixa() {
		return this.nomeCaixa;
	}

	public void setNomeCaixa(String nomeCaixa) {
		this.nomeCaixa = nomeCaixa;
	}

	public Integer getIdGeradoCaixa() {
		return this.idGeradoCaixa;
	}

	public void setIdGeradoCaixa(Integer idGeradoCaixa) {
		this.idGeradoCaixa = idGeradoCaixa;
	}

	public int getIdGerenteSupervisor() {
		return this.idGerenteSupervisor;
	}

	public void setIdGerenteSupervisor(int idGerenteSupervisor) {
		this.idGerenteSupervisor = idGerenteSupervisor;
	}

	public Date getDataAbertura() {
		return this.dataAbertura;
	}

	public void setDataAbertura(Date dataAbertura) {
		this.dataAbertura = dataAbertura;
	}

	public String getHoraAbertura() {
		return this.horaAbertura;
	}

	public void setHoraAbertura(String horaAbertura) {
		this.horaAbertura = horaAbertura;
	}

	public Date getDataFechamento() {
		return this.dataFechamento;
	}

	public void setDataFechamento(Date dataFechamento) {
		this.dataFechamento = dataFechamento;
	}

	public String getHoraFechamento() {
		return this.horaFechamento;
	}

	public void setHoraFechamento(String horaFechamento) {
		this.horaFechamento = horaFechamento;
	}

	public BigDecimal getTotalSuprimento() {
		return this.totalSuprimento;
	}

	public void setTotalSuprimento(BigDecimal totalSuprimento) {
		this.totalSuprimento = totalSuprimento;
	}

	public BigDecimal getTotalSangria() {
		return this.totalSangria;
	}

	public void setTotalSangria(BigDecimal totalSangria) {
		this.totalSangria = totalSangria;
	}

	public BigDecimal getTotalNaoFiscal() {
		return this.totalNaoFiscal;
	}

	public void setTotalNaoFiscal(BigDecimal totalNaoFiscal) {
		this.totalNaoFiscal = totalNaoFiscal;
	}

	public BigDecimal getTotalVenda() {
		return this.totalVenda;
	}

	public void setTotalVenda(BigDecimal totalVenda) {
		this.totalVenda = totalVenda;
	}

	public BigDecimal getTotalDesconto() {
		return this.totalDesconto;
	}

	public void setTotalDesconto(BigDecimal totalDesconto) {
		this.totalDesconto = totalDesconto;
	}

	public BigDecimal getTotalAcrescimo() {
		return this.totalAcrescimo;
	}

	public void setTotalAcrescimo(BigDecimal totalAcrescimo) {
		this.totalAcrescimo = totalAcrescimo;
	}

	public BigDecimal getTotalFinal() {
		return this.totalFinal;
	}

	public void setTotalFinal(BigDecimal totalFinal) {
		this.totalFinal = totalFinal;
	}

	public BigDecimal getTotalRecebido() {
		return this.totalRecebido;
	}

	public void setTotalRecebido(BigDecimal totalRecebido) {
		this.totalRecebido = totalRecebido;
	}

	public BigDecimal getTotalTroco() {
		return this.totalTroco;
	}

	public void setTotalTroco(BigDecimal totalTroco) {
		this.totalTroco = totalTroco;
	}

	public BigDecimal getTotalCancelado() {
		return this.totalCancelado;
	}

	public void setTotalCancelado(BigDecimal totalCancelado) {
		this.totalCancelado = totalCancelado;
	}

	public char getStatusMovimento() {
		return this.statusMovimento;
	}

	public void setStatusMovimento(char statusMovimento) {
		this.statusMovimento = statusMovimento;
	}

	public Character getSincronizado() {
		return this.sincronizado;
	}

	public void setSincronizado(Character sincronizado) {
		this.sincronizado = sincronizado;
	}

	public Date getDataSincronizacao() {
		return this.dataSincronizacao;
	}

	public void setDataSincronizacao(Date dataSincronizacao) {
		this.dataSincronizacao = dataSincronizacao;
	}

	public String getHoraSincronizacao() {
		return this.horaSincronizacao;
	}

	public void setHoraSincronizacao(String horaSincronizacao) {
		this.horaSincronizacao = horaSincronizacao;
	}

	public String getHashTripa() {
		return this.hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	public Integer getHashIncremento() {
		return this.hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}

	/**
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "ecfMovimento") public Set
	 *                  getEcfVendaCabecalhos() { return
	 *                  this.ecfVendaCabecalhos; }
	 * 
	 *                  public void setEcfVendaCabecalhos(Set
	 *                  ecfVendaCabecalhos) { this.ecfVendaCabecalhos =
	 *                  ecfVendaCabecalhos; }
	 * 
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "ecfMovimento") public Set
	 *                  getEcfFechamentos() { return this.ecfFechamentos; }
	 * 
	 *                  public void setEcfFechamentos(Set ecfFechamentos) {
	 *                  this.ecfFechamentos = ecfFechamentos; }
	 * 
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "ecfMovimento") public Set
	 *                  getEcfRecebimentoNaoFiscals() { return
	 *                  this.ecfRecebimentoNaoFiscals; }
	 * 
	 *                  public void setEcfRecebimentoNaoFiscals(Set
	 *                  ecfRecebimentoNaoFiscals) {
	 *                  this.ecfRecebimentoNaoFiscals =
	 *                  ecfRecebimentoNaoFiscals; }
	 */
}
