package br.com.rabelo.smartserver.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcfResolucao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_resolucao", catalog = "retaguarda")
public class EcfResolucao extends GenericDomain {
	@Column(name = "NOME_CAIXA", length = 30)
	private String nomeCaixa;

	@Column(name = "ID_GERADO_CAIXA")
	private Integer idGeradoCaixa;

	@Column(name = "ID_EMPRESA")
	private Integer idEmpresa;

	@Column(name = "RESOLUCAO_TELA", length = 20)
	private String resolucaoTela;

	@Column(name = "LARGURA")
	private Integer largura;

	@Column(name = "ALTURA")
	private Integer altura;

	@Column(name = "IMAGEM_TELA", length = 50)
	private String imagemTela;

	@Column(name = "IMAGEM_MENU", length = 50)
	private String imagemMenu;

	@Column(name = "IMAGEM_SUBMENU", length = 50)
	private String imagemSubmenu;

	@Column(name = "HOTTRACK_COLOR", length = 20)
	private String hottrackColor;

	@Column(name = "ITEM_STYLE_FONT_NAME", length = 20)
	private String itemStyleFontName;

	@Column(name = "ITEM_STYLE_FONT_COLOR", length = 20)
	private String itemStyleFontColor;

	@Column(name = "ITEM_SEL_STYLE_COLOR", length = 20)
	private String itemSelStyleColor;

	@Column(name = "LABEL_TOTAL_GERAL_FONT_COLOR", length = 20)
	private String labelTotalGeralFontColor;

	@Column(name = "ITEM_STYLE_FONT_STYLE", length = 20)
	private String itemStyleFontStyle;

	@Column(name = "EDITS_COLOR", length = 20)
	private String editsColor;

	@Column(name = "EDITS_FONT_COLOR", length = 20)
	private String editsFontColor;

	@Column(name = "EDITS_DISABLED_COLOR", length = 20)
	private String editsDisabledColor;

	@Column(name = "EDITS_FONT_NAME", length = 20)
	private String editsFontName;

	@Column(name = "EDITS_FONT_STYLE", length = 20)
	private String editsFontStyle;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_SINCRONIZACAO", length = 10)
	private Date dataSincronizacao;

	@Column(name = "HORA_SINCRONIZACAO", length = 8)
	private String horaSincronizacao;

	/** private Set ecfConfiguracaos = new HashSet(0); */

	public EcfResolucao() {
	}

	public EcfResolucao(String nomeCaixa, Integer idGeradoCaixa, Integer idEmpresa, String resolucaoTela,
			Integer largura, Integer altura, String imagemTela, String imagemMenu, String imagemSubmenu,
			String hottrackColor, String itemStyleFontName, String itemStyleFontColor, String itemSelStyleColor,
			String labelTotalGeralFontColor, String itemStyleFontStyle, String editsColor, String editsFontColor,
			String editsDisabledColor, String editsFontName, String editsFontStyle, Date dataSincronizacao,
			String horaSincronizacao/** , Set ecfConfiguracaos */
	) {
		this.nomeCaixa = nomeCaixa;
		this.idGeradoCaixa = idGeradoCaixa;
		this.idEmpresa = idEmpresa;
		this.resolucaoTela = resolucaoTela;
		this.largura = largura;
		this.altura = altura;
		this.imagemTela = imagemTela;
		this.imagemMenu = imagemMenu;
		this.imagemSubmenu = imagemSubmenu;
		this.hottrackColor = hottrackColor;
		this.itemStyleFontName = itemStyleFontName;
		this.itemStyleFontColor = itemStyleFontColor;
		this.itemSelStyleColor = itemSelStyleColor;
		this.labelTotalGeralFontColor = labelTotalGeralFontColor;
		this.itemStyleFontStyle = itemStyleFontStyle;
		this.editsColor = editsColor;
		this.editsFontColor = editsFontColor;
		this.editsDisabledColor = editsDisabledColor;
		this.editsFontName = editsFontName;
		this.editsFontStyle = editsFontStyle;
		this.dataSincronizacao = dataSincronizacao;
		this.horaSincronizacao = horaSincronizacao;
		/** this.ecfConfiguracaos = ecfConfiguracaos; */
	}

	public String getNomeCaixa() {
		return this.nomeCaixa;
	}

	public void setNomeCaixa(String nomeCaixa) {
		this.nomeCaixa = nomeCaixa;
	}

	public Integer getIdGeradoCaixa() {
		return this.idGeradoCaixa;
	}

	public void setIdGeradoCaixa(Integer idGeradoCaixa) {
		this.idGeradoCaixa = idGeradoCaixa;
	}

	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getResolucaoTela() {
		return this.resolucaoTela;
	}

	public void setResolucaoTela(String resolucaoTela) {
		this.resolucaoTela = resolucaoTela;
	}

	public Integer getLargura() {
		return this.largura;
	}

	public void setLargura(Integer largura) {
		this.largura = largura;
	}

	public Integer getAltura() {
		return this.altura;
	}

	public void setAltura(Integer altura) {
		this.altura = altura;
	}

	public String getImagemTela() {
		return this.imagemTela;
	}

	public void setImagemTela(String imagemTela) {
		this.imagemTela = imagemTela;
	}

	public String getImagemMenu() {
		return this.imagemMenu;
	}

	public void setImagemMenu(String imagemMenu) {
		this.imagemMenu = imagemMenu;
	}

	public String getImagemSubmenu() {
		return this.imagemSubmenu;
	}

	public void setImagemSubmenu(String imagemSubmenu) {
		this.imagemSubmenu = imagemSubmenu;
	}

	public String getHottrackColor() {
		return this.hottrackColor;
	}

	public void setHottrackColor(String hottrackColor) {
		this.hottrackColor = hottrackColor;
	}

	public String getItemStyleFontName() {
		return this.itemStyleFontName;
	}

	public void setItemStyleFontName(String itemStyleFontName) {
		this.itemStyleFontName = itemStyleFontName;
	}

	public String getItemStyleFontColor() {
		return this.itemStyleFontColor;
	}

	public void setItemStyleFontColor(String itemStyleFontColor) {
		this.itemStyleFontColor = itemStyleFontColor;
	}

	public String getItemSelStyleColor() {
		return this.itemSelStyleColor;
	}

	public void setItemSelStyleColor(String itemSelStyleColor) {
		this.itemSelStyleColor = itemSelStyleColor;
	}

	public String getLabelTotalGeralFontColor() {
		return this.labelTotalGeralFontColor;
	}

	public void setLabelTotalGeralFontColor(String labelTotalGeralFontColor) {
		this.labelTotalGeralFontColor = labelTotalGeralFontColor;
	}

	public String getItemStyleFontStyle() {
		return this.itemStyleFontStyle;
	}

	public void setItemStyleFontStyle(String itemStyleFontStyle) {
		this.itemStyleFontStyle = itemStyleFontStyle;
	}

	public String getEditsColor() {
		return this.editsColor;
	}

	public void setEditsColor(String editsColor) {
		this.editsColor = editsColor;
	}

	public String getEditsFontColor() {
		return this.editsFontColor;
	}

	public void setEditsFontColor(String editsFontColor) {
		this.editsFontColor = editsFontColor;
	}

	public String getEditsDisabledColor() {
		return this.editsDisabledColor;
	}

	public void setEditsDisabledColor(String editsDisabledColor) {
		this.editsDisabledColor = editsDisabledColor;
	}

	public String getEditsFontName() {
		return this.editsFontName;
	}

	public void setEditsFontName(String editsFontName) {
		this.editsFontName = editsFontName;
	}

	public String getEditsFontStyle() {
		return this.editsFontStyle;
	}

	public void setEditsFontStyle(String editsFontStyle) {
		this.editsFontStyle = editsFontStyle;
	}

	public Date getDataSincronizacao() {
		return this.dataSincronizacao;
	}

	public void setDataSincronizacao(Date dataSincronizacao) {
		this.dataSincronizacao = dataSincronizacao;
	}

	public String getHoraSincronizacao() {
		return this.horaSincronizacao;
	}

	public void setHoraSincronizacao(String horaSincronizacao) {
		this.horaSincronizacao = horaSincronizacao;
	}
	/**
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "ecfResolucao") public Set
	 *                  getEcfConfiguracaos() { return this.ecfConfiguracaos; }
	 * 
	 *                  public void setEcfConfiguracaos(Set ecfConfiguracaos) {
	 *                  this.ecfConfiguracaos = ecfConfiguracaos; }
	 */
}
