package br.com.rabelo.smartserver.domain;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcfRecebimentoNaoFiscal generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_recebimento_nao_fiscal", catalog = "retaguarda")
public class EcfRecebimentoNaoFiscal extends GenericDomain {
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_MOVIMENTO", nullable = false)
	private EcfMovimento ecfMovimento;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_RECEBIMENTO_NAO_FISCAL", nullable = false)
	private EcfTipoRecebimentoNaoFiscal ecfTipoRecebimentoNaoFiscal;

	@Column(name = "NOME_CAIXA", length = 30)
	private String nomeCaixa;

	@Column(name = "ID_GERADO_CAIXA")
	private Integer idGeradoCaixa;

	@Column(name = "ID_EMPRESA")
	private Integer idEmpresa;

	@Column(name = "ID_VENDA")
	private Integer idVenda;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_RECEBIMENTO", length = 10)
	private Date dataRecebimento;

	@Column(name = "HORA_RECEBIMENTO", length = 8)
	private String horaRecebimento;

	@Column(name = "SERIE_ECF", length = 20)
	private String serieEcf;

	@Column(name = "COO")
	private Integer coo;

	@Column(name = "CCF")
	private Integer ccf;

	@Column(name = "GNF")
	private Integer gnf;

	@Column(name = "DESCRICAO", length = 50)
	private String descricao;

	@Column(name = "VALOR", precision = 18, scale = 6)
	private BigDecimal valor;

	@Column(name = "TROCO", precision = 18, scale = 6)
	private BigDecimal troco;

	@Column(name = "STATUS_RECEBIMENTO", length = 1)
	private String statusRecebimento;

	@Column(name = "RECEBIMENTO_CANCELADO", length = 1)
	private String recebimentoCancelado;

	@Column(name = "SINCRONIZADO", length = 1)
	private Character sincronizado;

	@Column(name = "RECARGA_OPERADORA", length = 20)
	private String recargaOperadora;

	@Column(name = "RECARGA_DDDNUMERO", length = 15)
	private String recargaDddnumero;

	@Column(name = "RECARGA_AUTORIZACAO", length = 20)
	private String recargaAutorizacao;

	@Column(name = "RECARGA_NSU", length = 20)
	private String recargaNsu;

	@Column(name = "CODIGO_INTEGRACAO", length = 10)
	private String codigoIntegracao;

	@Column(name = "HASH_TRIPA", length = 32)
	private String hashTripa;

	@Column(name = "HASH_INCREMENTO")
	private Integer hashIncremento;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_SINCRONIZACAO", length = 10)
	private Date dataSincronizacao;

	@Column(name = "HORA_SINCRONIZACAO", length = 8)
	private String horaSincronizacao;

	@Column(name = "EXPORTADO", length = 1)
	private String exportado;

	public EcfRecebimentoNaoFiscal() {
	}

	public EcfRecebimentoNaoFiscal(EcfMovimento ecfMovimento, EcfTipoRecebimentoNaoFiscal ecfTipoRecebimentoNaoFiscal) {
		this.ecfMovimento = ecfMovimento;
		this.ecfTipoRecebimentoNaoFiscal = ecfTipoRecebimentoNaoFiscal;
	}

	public EcfRecebimentoNaoFiscal(EcfMovimento ecfMovimento, EcfTipoRecebimentoNaoFiscal ecfTipoRecebimentoNaoFiscal,
			String nomeCaixa, Integer idGeradoCaixa, Integer idEmpresa, Integer idVenda, Date dataRecebimento,
			String horaRecebimento, String serieEcf, Integer coo, Integer ccf, Integer gnf, String descricao,
			BigDecimal valor, BigDecimal troco, String statusRecebimento, String recebimentoCancelado,
			Character sincronizado, String recargaOperadora, String recargaDddnumero, String recargaAutorizacao,
			String recargaNsu, String codigoIntegracao, String hashTripa, Integer hashIncremento,
			Date dataSincronizacao, String horaSincronizacao, String exportado) {
		this.ecfMovimento = ecfMovimento;
		this.ecfTipoRecebimentoNaoFiscal = ecfTipoRecebimentoNaoFiscal;
		this.nomeCaixa = nomeCaixa;
		this.idGeradoCaixa = idGeradoCaixa;
		this.idEmpresa = idEmpresa;
		this.idVenda = idVenda;
		this.dataRecebimento = dataRecebimento;
		this.horaRecebimento = horaRecebimento;
		this.serieEcf = serieEcf;
		this.coo = coo;
		this.ccf = ccf;
		this.gnf = gnf;
		this.descricao = descricao;
		this.valor = valor;
		this.troco = troco;
		this.statusRecebimento = statusRecebimento;
		this.recebimentoCancelado = recebimentoCancelado;
		this.sincronizado = sincronizado;
		this.recargaOperadora = recargaOperadora;
		this.recargaDddnumero = recargaDddnumero;
		this.recargaAutorizacao = recargaAutorizacao;
		this.recargaNsu = recargaNsu;
		this.codigoIntegracao = codigoIntegracao;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
		this.dataSincronizacao = dataSincronizacao;
		this.horaSincronizacao = horaSincronizacao;
		this.exportado = exportado;
	}

	public EcfMovimento getEcfMovimento() {
		return this.ecfMovimento;
	}

	public void setEcfMovimento(EcfMovimento ecfMovimento) {
		this.ecfMovimento = ecfMovimento;
	}

	public EcfTipoRecebimentoNaoFiscal getEcfTipoRecebimentoNaoFiscal() {
		return this.ecfTipoRecebimentoNaoFiscal;
	}

	public void setEcfTipoRecebimentoNaoFiscal(EcfTipoRecebimentoNaoFiscal ecfTipoRecebimentoNaoFiscal) {
		this.ecfTipoRecebimentoNaoFiscal = ecfTipoRecebimentoNaoFiscal;
	}

	public String getNomeCaixa() {
		return this.nomeCaixa;
	}

	public void setNomeCaixa(String nomeCaixa) {
		this.nomeCaixa = nomeCaixa;
	}

	public Integer getIdGeradoCaixa() {
		return this.idGeradoCaixa;
	}

	public void setIdGeradoCaixa(Integer idGeradoCaixa) {
		this.idGeradoCaixa = idGeradoCaixa;
	}

	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public Integer getIdVenda() {
		return this.idVenda;
	}

	public void setIdVenda(Integer idVenda) {
		this.idVenda = idVenda;
	}

	public Date getDataRecebimento() {
		return this.dataRecebimento;
	}

	public void setDataRecebimento(Date dataRecebimento) {
		this.dataRecebimento = dataRecebimento;
	}

	public String getHoraRecebimento() {
		return this.horaRecebimento;
	}

	public void setHoraRecebimento(String horaRecebimento) {
		this.horaRecebimento = horaRecebimento;
	}

	public String getSerieEcf() {
		return this.serieEcf;
	}

	public void setSerieEcf(String serieEcf) {
		this.serieEcf = serieEcf;
	}

	public Integer getCoo() {
		return this.coo;
	}

	public void setCoo(Integer coo) {
		this.coo = coo;
	}

	public Integer getCcf() {
		return this.ccf;
	}

	public void setCcf(Integer ccf) {
		this.ccf = ccf;
	}

	public Integer getGnf() {
		return this.gnf;
	}

	public void setGnf(Integer gnf) {
		this.gnf = gnf;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public BigDecimal getTroco() {
		return this.troco;
	}

	public void setTroco(BigDecimal troco) {
		this.troco = troco;
	}

	public String getStatusRecebimento() {
		return this.statusRecebimento;
	}

	public void setStatusRecebimento(String statusRecebimento) {
		this.statusRecebimento = statusRecebimento;
	}

	public String getRecebimentoCancelado() {
		return this.recebimentoCancelado;
	}

	public void setRecebimentoCancelado(String recebimentoCancelado) {
		this.recebimentoCancelado = recebimentoCancelado;
	}

	public Character getSincronizado() {
		return this.sincronizado;
	}

	public void setSincronizado(Character sincronizado) {
		this.sincronizado = sincronizado;
	}

	public String getRecargaOperadora() {
		return this.recargaOperadora;
	}

	public void setRecargaOperadora(String recargaOperadora) {
		this.recargaOperadora = recargaOperadora;
	}

	public String getRecargaDddnumero() {
		return this.recargaDddnumero;
	}

	public void setRecargaDddnumero(String recargaDddnumero) {
		this.recargaDddnumero = recargaDddnumero;
	}

	public String getRecargaAutorizacao() {
		return this.recargaAutorizacao;
	}

	public void setRecargaAutorizacao(String recargaAutorizacao) {
		this.recargaAutorizacao = recargaAutorizacao;
	}

	public String getRecargaNsu() {
		return this.recargaNsu;
	}

	public void setRecargaNsu(String recargaNsu) {
		this.recargaNsu = recargaNsu;
	}

	public String getCodigoIntegracao() {
		return this.codigoIntegracao;
	}

	public void setCodigoIntegracao(String codigoIntegracao) {
		this.codigoIntegracao = codigoIntegracao;
	}

	public String getHashTripa() {
		return this.hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	public Integer getHashIncremento() {
		return this.hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}

	public Date getDataSincronizacao() {
		return this.dataSincronizacao;
	}

	public void setDataSincronizacao(Date dataSincronizacao) {
		this.dataSincronizacao = dataSincronizacao;
	}

	public String getHoraSincronizacao() {
		return this.horaSincronizacao;
	}

	public void setHoraSincronizacao(String horaSincronizacao) {
		this.horaSincronizacao = horaSincronizacao;
	}

	public String getExportado() {
		return this.exportado;
	}

	public void setExportado(String exportado) {
		this.exportado = exportado;
	}

}
