package br.com.rabelo.smartserver.domain;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EcfRecebimentoNaoFiscalPagamento generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_recebimento_nao_fiscal_pagamento", catalog = "retaguarda")
public class EcfRecebimentoNaoFiscalPagamento extends GenericDomain {
	@Column(name = "ID_ECF_RECEBIMENTO_NAO_FISCAL", nullable = false)
	private int idEcfRecebimentoNaoFiscal;

	@Column(name = "ID_ECF_TIPO_PAGAMENTO", nullable = false)
	private int idEcfTipoPagamento;

	@Column(name = "SERIE_ECF", length = 20)
	private String serieEcf;

	@Column(name = "COO")
	private Integer coo;

	@Column(name = "CCF")
	private Integer ccf;

	@Column(name = "GNF")
	private Integer gnf;

	@Column(name = "VALOR", precision = 18, scale = 6)
	private BigDecimal valor;

	@Column(name = "NUMERO_CARTAO", length = 16)
	private String numeroCartao;

	@Column(name = "NSU", length = 30)
	private String nsu;

	@Column(name = "AUTORIZACAO", length = 30)
	private String autorizacao;

	@Column(name = "ESTORNO", length = 1)
	private Character estorno;

	@Column(name = "REDE", length = 30)
	private String rede;

	@Column(name = "CARTAO_DC", length = 1)
	private Character cartaoDc;

	@Column(name = "PARCELADO_POR", length = 1)
	private String parceladoPor;

	@Column(name = "QTD_PARCELAS")
	private Integer qtdParcelas;

	@Column(name = "SINCRONIZADO", length = 1)
	private Character sincronizado;

	@Column(name = "HASH_TRIPA", length = 32)
	private String hashTripa;

	@Column(name = "HASH_INCREMENTO")
	private Integer hashIncremento;

	@Column(name = "ID_GERADO_CAIXA")
	private Integer idGeradoCaixa;

	@Column(name = "EXPORTADO", length = 1)
	private String exportado;

	@Column(name = "NSU_HOST", length = 30)
	private String nsuHost;

	@Column(name = "NSU_SITEF", length = 30)
	private String nsuSitef;

	public EcfRecebimentoNaoFiscalPagamento() {
	}

	public EcfRecebimentoNaoFiscalPagamento(int idEcfRecebimentoNaoFiscal, int idEcfTipoPagamento) {
		this.idEcfRecebimentoNaoFiscal = idEcfRecebimentoNaoFiscal;
		this.idEcfTipoPagamento = idEcfTipoPagamento;
	}

	public EcfRecebimentoNaoFiscalPagamento(int idEcfRecebimentoNaoFiscal, int idEcfTipoPagamento, String serieEcf,
			Integer coo, Integer ccf, Integer gnf, BigDecimal valor, String numeroCartao, String nsu,
			String autorizacao, Character estorno, String rede, Character cartaoDc, String parceladoPor,
			Integer qtdParcelas, Character sincronizado, String hashTripa, Integer hashIncremento,
			Integer idGeradoCaixa, String exportado, String nsuHost, String nsuSitef) {
		this.idEcfRecebimentoNaoFiscal = idEcfRecebimentoNaoFiscal;
		this.idEcfTipoPagamento = idEcfTipoPagamento;
		this.serieEcf = serieEcf;
		this.coo = coo;
		this.ccf = ccf;
		this.gnf = gnf;
		this.valor = valor;
		this.numeroCartao = numeroCartao;
		this.nsu = nsu;
		this.autorizacao = autorizacao;
		this.estorno = estorno;
		this.rede = rede;
		this.cartaoDc = cartaoDc;
		this.parceladoPor = parceladoPor;
		this.qtdParcelas = qtdParcelas;
		this.sincronizado = sincronizado;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
		this.idGeradoCaixa = idGeradoCaixa;
		this.exportado = exportado;
		this.nsuHost = nsuHost;
		this.nsuSitef = nsuSitef;
	}

	public int getIdEcfRecebimentoNaoFiscal() {
		return this.idEcfRecebimentoNaoFiscal;
	}

	public void setIdEcfRecebimentoNaoFiscal(int idEcfRecebimentoNaoFiscal) {
		this.idEcfRecebimentoNaoFiscal = idEcfRecebimentoNaoFiscal;
	}

	public int getIdEcfTipoPagamento() {
		return this.idEcfTipoPagamento;
	}

	public void setIdEcfTipoPagamento(int idEcfTipoPagamento) {
		this.idEcfTipoPagamento = idEcfTipoPagamento;
	}

	public String getSerieEcf() {
		return this.serieEcf;
	}

	public void setSerieEcf(String serieEcf) {
		this.serieEcf = serieEcf;
	}

	public Integer getCoo() {
		return this.coo;
	}

	public void setCoo(Integer coo) {
		this.coo = coo;
	}

	public Integer getCcf() {
		return this.ccf;
	}

	public void setCcf(Integer ccf) {
		this.ccf = ccf;
	}

	public Integer getGnf() {
		return this.gnf;
	}

	public void setGnf(Integer gnf) {
		this.gnf = gnf;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public String getNumeroCartao() {
		return this.numeroCartao;
	}

	public void setNumeroCartao(String numeroCartao) {
		this.numeroCartao = numeroCartao;
	}

	public String getNsu() {
		return this.nsu;
	}

	public void setNsu(String nsu) {
		this.nsu = nsu;
	}

	public String getAutorizacao() {
		return this.autorizacao;
	}

	public void setAutorizacao(String autorizacao) {
		this.autorizacao = autorizacao;
	}

	public Character getEstorno() {
		return this.estorno;
	}

	public void setEstorno(Character estorno) {
		this.estorno = estorno;
	}

	public String getRede() {
		return this.rede;
	}

	public void setRede(String rede) {
		this.rede = rede;
	}

	public Character getCartaoDc() {
		return this.cartaoDc;
	}

	public void setCartaoDc(Character cartaoDc) {
		this.cartaoDc = cartaoDc;
	}

	public String getParceladoPor() {
		return this.parceladoPor;
	}

	public void setParceladoPor(String parceladoPor) {
		this.parceladoPor = parceladoPor;
	}

	public Integer getQtdParcelas() {
		return this.qtdParcelas;
	}

	public void setQtdParcelas(Integer qtdParcelas) {
		this.qtdParcelas = qtdParcelas;
	}

	public Character getSincronizado() {
		return this.sincronizado;
	}

	public void setSincronizado(Character sincronizado) {
		this.sincronizado = sincronizado;
	}

	public String getHashTripa() {
		return this.hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	public Integer getHashIncremento() {
		return this.hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}

	public Integer getIdGeradoCaixa() {
		return this.idGeradoCaixa;
	}

	public void setIdGeradoCaixa(Integer idGeradoCaixa) {
		this.idGeradoCaixa = idGeradoCaixa;
	}

	public String getExportado() {
		return this.exportado;
	}

	public void setExportado(String exportado) {
		this.exportado = exportado;
	}

	public String getNsuHost() {
		return this.nsuHost;
	}

	public void setNsuHost(String nsuHost) {
		this.nsuHost = nsuHost;
	}

	public String getNsuSitef() {
		return this.nsuSitef;
	}

	public void setNsuSitef(String nsuSitef) {
		this.nsuSitef = nsuSitef;
	}

}
