package br.com.rabelo.smartserver.domain;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcfSangria generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_sangria", catalog = "retaguarda")
public class EcfSangria extends GenericDomain {
	@Column(name = "NOME_CAIXA", length = 30)
	private String nomeCaixa;

	@Column(name = "ID_GERADO_CAIXA")
	private Integer idGeradoCaixa;

	@Column(name = "ID_EMPRESA")
	private Integer idEmpresa;

	@Column(name = "ID_ECF_MOVIMENTO")
	private Integer idEcfMovimento;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_SANGRIA", length = 10)
	private Date dataSangria;

	@Column(name = "VALOR", precision = 18, scale = 6)
	private BigDecimal valor;

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_SINCRONIZACAO", length = 10)
	private Date dataSincronizacao;

	@Column(name = "HORA_SINCRONIZACAO", length = 8)
	private String horaSincronizacao;

	@Column(name = "HASH_TRIPA", length = 32)
	private String hashTripa;

	@Column(name = "HASH_INCREMENTO")
	private Integer hashIncremento;

	public EcfSangria() {
	}

	public EcfSangria(String nomeCaixa, Integer idGeradoCaixa, Integer idEmpresa, Integer idEcfMovimento,
			Date dataSangria, BigDecimal valor, Date dataSincronizacao, String horaSincronizacao, String hashTripa,
			Integer hashIncremento) {
		this.nomeCaixa = nomeCaixa;
		this.idGeradoCaixa = idGeradoCaixa;
		this.idEmpresa = idEmpresa;
		this.idEcfMovimento = idEcfMovimento;
		this.dataSangria = dataSangria;
		this.valor = valor;
		this.dataSincronizacao = dataSincronizacao;
		this.horaSincronizacao = horaSincronizacao;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
	}

	public String getNomeCaixa() {
		return this.nomeCaixa;
	}

	public void setNomeCaixa(String nomeCaixa) {
		this.nomeCaixa = nomeCaixa;
	}

	public Integer getIdGeradoCaixa() {
		return this.idGeradoCaixa;
	}

	public void setIdGeradoCaixa(Integer idGeradoCaixa) {
		this.idGeradoCaixa = idGeradoCaixa;
	}

	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public Integer getIdEcfMovimento() {
		return this.idEcfMovimento;
	}

	public void setIdEcfMovimento(Integer idEcfMovimento) {
		this.idEcfMovimento = idEcfMovimento;
	}

	public Date getDataSangria() {
		return this.dataSangria;
	}

	public void setDataSangria(Date dataSangria) {
		this.dataSangria = dataSangria;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public Date getDataSincronizacao() {
		return this.dataSincronizacao;
	}

	public void setDataSincronizacao(Date dataSincronizacao) {
		this.dataSincronizacao = dataSincronizacao;
	}

	public String getHoraSincronizacao() {
		return this.horaSincronizacao;
	}

	public void setHoraSincronizacao(String horaSincronizacao) {
		this.horaSincronizacao = horaSincronizacao;
	}

	public String getHashTripa() {
		return this.hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	public Integer getHashIncremento() {
		return this.hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}

}
