package br.com.rabelo.smartserver.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EcfTipoRecebimentoNaoFiscal generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_tipo_recebimento_nao_fiscal", catalog = "retaguarda")
public class EcfTipoRecebimentoNaoFiscal extends GenericDomain {
	@Column(name = "Codigo", length = 3)
	private String codigo;

	@Column(name = "Descricao", length = 20)
	private String descricao;

	/** private Set ecfRecebimentoNaoFiscals = new HashSet(0); */

	public EcfTipoRecebimentoNaoFiscal() {
	}

	public EcfTipoRecebimentoNaoFiscal(String codigo,
			String descricao/** , Set ecfRecebimentoNaoFiscals */
	) {
		this.codigo = codigo;
		this.descricao = descricao;
		/** this.ecfRecebimentoNaoFiscals = ecfRecebimentoNaoFiscals; */
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	/**
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy =
	 *                  "ecfTipoRecebimentoNaoFiscal") public Set
	 *                  getEcfRecebimentoNaoFiscals() { return
	 *                  this.ecfRecebimentoNaoFiscals; }
	 * 
	 *                  public void setEcfRecebimentoNaoFiscals(Set
	 *                  ecfRecebimentoNaoFiscals) {
	 *                  this.ecfRecebimentoNaoFiscals =
	 *                  ecfRecebimentoNaoFiscals; }
	 */
}
