package br.com.rabelo.smartserver.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EcfTipoPagamento generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_tipo_pagamento", catalog = "retaguarda")
public class EcfTipoPagamento extends GenericDomain {
	@Column(name = "CODIGO", length = 3)
	private Character codigo;

	@Column(name = "DESCRICAO", length = 20)
	private String descricao;

	@Column(name = "TEF", length = 1)
	private Character tef;

	@Column(name = "IMPRIME_VINCULADO", length = 1)
	private Character imprimeVinculado;

	@Column(name = "PERMITE_TROCO", length = 1)
	private Character permiteTroco;

	@Column(name = "TEF_TIPO_GP", length = 1)
	private Character tefTipoGp;

	@Column(name = "GERA_PARCELAS", length = 1)
	private Character geraParcelas;

	/** private Set ecfVendaPagamentos = new HashSet(0); */

	public EcfTipoPagamento() {
	}

	public EcfTipoPagamento(Character codigo, String descricao, Character tef, Character imprimeVinculado,
			Character permiteTroco, Character tefTipoGp,
			Character geraParcelas/** , Set ecfVendaPagamentos */
	) {
		this.codigo = codigo;
		this.descricao = descricao;
		this.tef = tef;
		this.imprimeVinculado = imprimeVinculado;
		this.permiteTroco = permiteTroco;
		this.tefTipoGp = tefTipoGp;
		this.geraParcelas = geraParcelas;
		/** this.ecfVendaPagamentos = ecfVendaPagamentos; */
	}

	public Character getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Character codigo) {
		this.codigo = codigo;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Character getTef() {
		return this.tef;
	}

	public void setTef(Character tef) {
		this.tef = tef;
	}

	public Character getImprimeVinculado() {
		return this.imprimeVinculado;
	}

	public void setImprimeVinculado(Character imprimeVinculado) {
		this.imprimeVinculado = imprimeVinculado;
	}

	public Character getPermiteTroco() {
		return this.permiteTroco;
	}

	public void setPermiteTroco(Character permiteTroco) {
		this.permiteTroco = permiteTroco;
	}

	public Character getTefTipoGp() {
		return this.tefTipoGp;
	}

	public void setTefTipoGp(Character tefTipoGp) {
		this.tefTipoGp = tefTipoGp;
	}

	public Character getGeraParcelas() {
		return this.geraParcelas;
	}

	public void setGeraParcelas(Character geraParcelas) {
		this.geraParcelas = geraParcelas;
	}

	/**
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "ecfTipoPagamento") public
	 *                  Set getEcfVendaPagamentos() { return
	 *                  this.ecfVendaPagamentos; }
	 * 
	 *                  public void setEcfVendaPagamentos(Set
	 *                  ecfVendaPagamentos) { this.ecfVendaPagamentos =
	 *                  ecfVendaPagamentos; }
	 */
}
