package br.com.rabelo.smartserver.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EcfTipoRelatorioGerencial generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_tipo_relatorio_gerencial", catalog = "retaguarda")
public class EcfTipoRelatorioGerencial extends GenericDomain {
	@Column(name = "Codigo", length = 3)
	private String codigo;

	@Column(name = "Descricao", length = 20)
	private String descricao;

	@Column(name = "HASH_TRIPA", length = 32)
	private String hashTripa;

	@Column(name = "HASH_INCREMENTO")
	private Integer hashIncremento;

	public EcfTipoRelatorioGerencial() {
	}

	public EcfTipoRelatorioGerencial(String codigo, String descricao, String hashTripa, Integer hashIncremento) {
		this.codigo = codigo;
		this.descricao = descricao;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getHashTripa() {
		return this.hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	public Integer getHashIncremento() {
		return this.hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}

}
