package br.com.rabelo.smartserver.domain;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcfVendaCabecalho generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ecf_venda_cabecalho", catalog = "retaguarda")
public class EcfVendaCabecalho extends GenericDomain {

	private EcfMovimento ecfMovimento;
	private String nomeCaixa;
	private Integer idGeradoCaixa;
	private Integer idEmpresa;
	private Integer idCliente;
	private Integer idEcfFuncionario;
	private Integer idVendedor;
	private Integer idEcfDav;
	private Integer idEcfPreVendaCabecalho;
	private String serieEcf;
	private int cfop;
	private Integer coo;
	private Integer ccf;
	private Date dataVenda;
	private String horaVenda;
	private BigDecimal valorVenda;
	private BigDecimal taxaDesconto;
	private BigDecimal desconto;
	private BigDecimal taxaAcrescimo;
	private BigDecimal acrescimo;
	private BigDecimal valorFinal;
	private BigDecimal valorRecebido;
	private BigDecimal troco;
	private BigDecimal valorCancelado;
	private Character sincronizado;
	private BigDecimal totalProdutos;
	private BigDecimal totalDocumento;
	private BigDecimal totalRecebimentoNaoFiscal;
	private BigDecimal baseIcms;
	private BigDecimal icms;
	private BigDecimal icmsOutras;
	private BigDecimal issqn;
	private BigDecimal pis;
	private BigDecimal cofins;
	private BigDecimal acrescimoItens;
	private BigDecimal descontoItens;
	private Character statusVenda;
	private String nomeCliente;
	private String cpfCnpjCliente;
	private Character cupomCancelado;
	private String observacao;
	private String hashTripa;
	private Integer hashIncremento;
	private BigDecimal icmsIsento;
	private BigDecimal icmsSubstituicao;
	private BigDecimal icmsNaoTributado;
	private String numeroNotaManual;
	private Date dataSincronizacao;
	private String horaSincronizacao;
	private String exportado;

	public EcfVendaCabecalho() {
	}

	public EcfVendaCabecalho(EcfMovimento ecfMovimento, int cfop) {
		this.ecfMovimento = ecfMovimento;
		this.cfop = cfop;
	}

	public EcfVendaCabecalho(EcfMovimento ecfMovimento, String nomeCaixa, Integer idGeradoCaixa, Integer idEmpresa,
			Integer idCliente, Integer idEcfFuncionario, Integer idVendedor, Integer idEcfDav,
			Integer idEcfPreVendaCabecalho, String serieEcf, int cfop, Integer coo, Integer ccf, Date dataVenda,
			String horaVenda, BigDecimal valorVenda, BigDecimal taxaDesconto, BigDecimal desconto,
			BigDecimal taxaAcrescimo, BigDecimal acrescimo, BigDecimal valorFinal, BigDecimal valorRecebido,
			BigDecimal troco, BigDecimal valorCancelado, Character sincronizado, BigDecimal totalProdutos,
			BigDecimal totalDocumento, BigDecimal totalRecebimentoNaoFiscal, BigDecimal baseIcms, BigDecimal icms,
			BigDecimal icmsOutras, BigDecimal issqn, BigDecimal pis, BigDecimal cofins, BigDecimal acrescimoItens,
			BigDecimal descontoItens, Character statusVenda, String nomeCliente, String cpfCnpjCliente,
			Character cupomCancelado, String observacao, String hashTripa, Integer hashIncremento,
			BigDecimal icmsIsento, BigDecimal icmsSubstituicao, BigDecimal icmsNaoTributado, String numeroNotaManual,
			Date dataSincronizacao, String horaSincronizacao, String exportado) {
		this.ecfMovimento = ecfMovimento;
		this.nomeCaixa = nomeCaixa;
		this.idGeradoCaixa = idGeradoCaixa;
		this.idEmpresa = idEmpresa;
		this.idCliente = idCliente;
		this.idEcfFuncionario = idEcfFuncionario;
		this.idVendedor = idVendedor;
		this.idEcfDav = idEcfDav;
		this.idEcfPreVendaCabecalho = idEcfPreVendaCabecalho;
		this.serieEcf = serieEcf;
		this.cfop = cfop;
		this.coo = coo;
		this.ccf = ccf;
		this.dataVenda = dataVenda;
		this.horaVenda = horaVenda;
		this.valorVenda = valorVenda;
		this.taxaDesconto = taxaDesconto;
		this.desconto = desconto;
		this.taxaAcrescimo = taxaAcrescimo;
		this.acrescimo = acrescimo;
		this.valorFinal = valorFinal;
		this.valorRecebido = valorRecebido;
		this.troco = troco;
		this.valorCancelado = valorCancelado;
		this.sincronizado = sincronizado;
		this.totalProdutos = totalProdutos;
		this.totalDocumento = totalDocumento;
		this.totalRecebimentoNaoFiscal = totalRecebimentoNaoFiscal;
		this.baseIcms = baseIcms;
		this.icms = icms;
		this.icmsOutras = icmsOutras;
		this.issqn = issqn;
		this.pis = pis;
		this.cofins = cofins;
		this.acrescimoItens = acrescimoItens;
		this.descontoItens = descontoItens;
		this.statusVenda = statusVenda;
		this.nomeCliente = nomeCliente;
		this.cpfCnpjCliente = cpfCnpjCliente;
		this.cupomCancelado = cupomCancelado;
		this.observacao = observacao;
		this.hashTripa = hashTripa;
		this.hashIncremento = hashIncremento;
		this.icmsIsento = icmsIsento;
		this.icmsSubstituicao = icmsSubstituicao;
		this.icmsNaoTributado = icmsNaoTributado;
		this.numeroNotaManual = numeroNotaManual;
		this.dataSincronizacao = dataSincronizacao;
		this.horaSincronizacao = horaSincronizacao;
		this.exportado = exportado;

	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECF_MOVIMENTO", nullable = false)
	public EcfMovimento getEcfMovimento() {
		return this.ecfMovimento;
	}

	public void setEcfMovimento(EcfMovimento ecfMovimento) {
		this.ecfMovimento = ecfMovimento;
	}

	@Column(name = "NOME_CAIXA", length = 30)
	public String getNomeCaixa() {
		return this.nomeCaixa;
	}

	public void setNomeCaixa(String nomeCaixa) {
		this.nomeCaixa = nomeCaixa;
	}

	@Column(name = "ID_GERADO_CAIXA")
	public Integer getIdGeradoCaixa() {
		return this.idGeradoCaixa;
	}

	public void setIdGeradoCaixa(Integer idGeradoCaixa) {
		this.idGeradoCaixa = idGeradoCaixa;
	}

	@Column(name = "ID_EMPRESA")
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "ID_CLIENTE")
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "ID_ECF_FUNCIONARIO")
	public Integer getIdEcfFuncionario() {
		return this.idEcfFuncionario;
	}

	public void setIdEcfFuncionario(Integer idEcfFuncionario) {
		this.idEcfFuncionario = idEcfFuncionario;
	}

	@Column(name = "ID_VENDEDOR")
	public Integer getIdVendedor() {
		return this.idVendedor;
	}

	public void setIdVendedor(Integer idVendedor) {
		this.idVendedor = idVendedor;
	}

	@Column(name = "ID_ECF_DAV")
	public Integer getIdEcfDav() {
		return this.idEcfDav;
	}

	public void setIdEcfDav(Integer idEcfDav) {
		this.idEcfDav = idEcfDav;
	}

	@Column(name = "ID_ECF_PRE_VENDA_CABECALHO")
	public Integer getIdEcfPreVendaCabecalho() {
		return this.idEcfPreVendaCabecalho;
	}

	public void setIdEcfPreVendaCabecalho(Integer idEcfPreVendaCabecalho) {
		this.idEcfPreVendaCabecalho = idEcfPreVendaCabecalho;
	}

	@Column(name = "SERIE_ECF", length = 20)
	public String getSerieEcf() {
		return this.serieEcf;
	}

	public void setSerieEcf(String serieEcf) {
		this.serieEcf = serieEcf;
	}

	@Column(name = "CFOP", nullable = false)
	public int getCfop() {
		return this.cfop;
	}

	public void setCfop(int cfop) {
		this.cfop = cfop;
	}

	@Column(name = "COO")
	public Integer getCoo() {
		return this.coo;
	}

	public void setCoo(Integer coo) {
		this.coo = coo;
	}

	@Column(name = "CCF")
	public Integer getCcf() {
		return this.ccf;
	}

	public void setCcf(Integer ccf) {
		this.ccf = ccf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_VENDA", length = 10)
	public Date getDataVenda() {
		return this.dataVenda;
	}

	public void setDataVenda(Date dataVenda) {
		this.dataVenda = dataVenda;
	}

	@Column(name = "HORA_VENDA", length = 8)
	public String getHoraVenda() {
		return this.horaVenda;
	}

	public void setHoraVenda(String horaVenda) {
		this.horaVenda = horaVenda;
	}

	@Column(name = "VALOR_VENDA", precision = 18, scale = 6)
	public BigDecimal getValorVenda() {
		return this.valorVenda;
	}

	public void setValorVenda(BigDecimal valorVenda) {
		this.valorVenda = valorVenda;
	}

	@Column(name = "TAXA_DESCONTO", precision = 18, scale = 6)
	public BigDecimal getTaxaDesconto() {
		return this.taxaDesconto;
	}

	public void setTaxaDesconto(BigDecimal taxaDesconto) {
		this.taxaDesconto = taxaDesconto;
	}

	@Column(name = "DESCONTO", precision = 18, scale = 6)
	public BigDecimal getDesconto() {
		return this.desconto;
	}

	public void setDesconto(BigDecimal desconto) {
		this.desconto = desconto;
	}

	@Column(name = "TAXA_ACRESCIMO", precision = 18, scale = 6)
	public BigDecimal getTaxaAcrescimo() {
		return this.taxaAcrescimo;
	}

	public void setTaxaAcrescimo(BigDecimal taxaAcrescimo) {
		this.taxaAcrescimo = taxaAcrescimo;
	}

	@Column(name = "ACRESCIMO", precision = 18, scale = 6)
	public BigDecimal getAcrescimo() {
		return this.acrescimo;
	}

	public void setAcrescimo(BigDecimal acrescimo) {
		this.acrescimo = acrescimo;
	}

	@Column(name = "VALOR_FINAL", precision = 18, scale = 6)
	public BigDecimal getValorFinal() {
		return this.valorFinal;
	}

	public void setValorFinal(BigDecimal valorFinal) {
		this.valorFinal = valorFinal;
	}

	@Column(name = "VALOR_RECEBIDO", precision = 18, scale = 6)
	public BigDecimal getValorRecebido() {
		return this.valorRecebido;
	}

	public void setValorRecebido(BigDecimal valorRecebido) {
		this.valorRecebido = valorRecebido;
	}

	@Column(name = "TROCO", precision = 18, scale = 6)
	public BigDecimal getTroco() {
		return this.troco;
	}

	public void setTroco(BigDecimal troco) {
		this.troco = troco;
	}

	@Column(name = "VALOR_CANCELADO", precision = 18, scale = 6)
	public BigDecimal getValorCancelado() {
		return this.valorCancelado;
	}

	public void setValorCancelado(BigDecimal valorCancelado) {
		this.valorCancelado = valorCancelado;
	}

	@Column(name = "SINCRONIZADO", length = 1)
	public Character getSincronizado() {
		return this.sincronizado;
	}

	public void setSincronizado(Character sincronizado) {
		this.sincronizado = sincronizado;
	}

	@Column(name = "TOTAL_PRODUTOS", precision = 18, scale = 6)
	public BigDecimal getTotalProdutos() {
		return this.totalProdutos;
	}

	public void setTotalProdutos(BigDecimal totalProdutos) {
		this.totalProdutos = totalProdutos;
	}

	@Column(name = "TOTAL_DOCUMENTO", precision = 18, scale = 6)
	public BigDecimal getTotalDocumento() {
		return this.totalDocumento;
	}

	public void setTotalDocumento(BigDecimal totalDocumento) {
		this.totalDocumento = totalDocumento;
	}

	@Column(name = "TOTAL_RECEBIMENTO_NAO_FISCAL", precision = 18, scale = 6)
	public BigDecimal getTotalRecebimentoNaoFiscal() {
		return this.totalRecebimentoNaoFiscal;
	}

	public void setTotalRecebimentoNaoFiscal(BigDecimal totalRecebimentoNaoFiscal) {
		this.totalRecebimentoNaoFiscal = totalRecebimentoNaoFiscal;
	}

	@Column(name = "BASE_ICMS", precision = 18, scale = 6)
	public BigDecimal getBaseIcms() {
		return this.baseIcms;
	}

	public void setBaseIcms(BigDecimal baseIcms) {
		this.baseIcms = baseIcms;
	}

	@Column(name = "ICMS", precision = 18, scale = 6)
	public BigDecimal getIcms() {
		return this.icms;
	}

	public void setIcms(BigDecimal icms) {
		this.icms = icms;
	}

	@Column(name = "ICMS_OUTRAS", precision = 18, scale = 6)
	public BigDecimal getIcmsOutras() {
		return this.icmsOutras;
	}

	public void setIcmsOutras(BigDecimal icmsOutras) {
		this.icmsOutras = icmsOutras;
	}

	@Column(name = "ISSQN", precision = 18, scale = 6)
	public BigDecimal getIssqn() {
		return this.issqn;
	}

	public void setIssqn(BigDecimal issqn) {
		this.issqn = issqn;
	}

	@Column(name = "PIS", precision = 18, scale = 6)
	public BigDecimal getPis() {
		return this.pis;
	}

	public void setPis(BigDecimal pis) {
		this.pis = pis;
	}

	@Column(name = "COFINS", precision = 18, scale = 6)
	public BigDecimal getCofins() {
		return this.cofins;
	}

	public void setCofins(BigDecimal cofins) {
		this.cofins = cofins;
	}

	@Column(name = "ACRESCIMO_ITENS", precision = 18, scale = 6)
	public BigDecimal getAcrescimoItens() {
		return this.acrescimoItens;
	}

	public void setAcrescimoItens(BigDecimal acrescimoItens) {
		this.acrescimoItens = acrescimoItens;
	}

	@Column(name = "DESCONTO_ITENS", precision = 18, scale = 6)
	public BigDecimal getDescontoItens() {
		return this.descontoItens;
	}

	public void setDescontoItens(BigDecimal descontoItens) {
		this.descontoItens = descontoItens;
	}

	@Column(name = "STATUS_VENDA", length = 1)
	public Character getStatusVenda() {
		return this.statusVenda;
	}

	public void setStatusVenda(Character statusVenda) {
		this.statusVenda = statusVenda;
	}

	@Column(name = "NOME_CLIENTE", length = 100)
	public String getNomeCliente() {
		return this.nomeCliente;
	}

	public void setNomeCliente(String nomeCliente) {
		this.nomeCliente = nomeCliente;
	}

	@Column(name = "CPF_CNPJ_CLIENTE", length = 14)
	public String getCpfCnpjCliente() {
		return this.cpfCnpjCliente;
	}

	public void setCpfCnpjCliente(String cpfCnpjCliente) {
		this.cpfCnpjCliente = cpfCnpjCliente;
	}

	@Column(name = "CUPOM_CANCELADO", length = 1)
	public Character getCupomCancelado() {
		return this.cupomCancelado;
	}

	public void setCupomCancelado(Character cupomCancelado) {
		this.cupomCancelado = cupomCancelado;
	}

	@Column(name = "OBSERVACAO", length = 100)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "HASH_TRIPA", length = 32)
	public String getHashTripa() {
		return this.hashTripa;
	}

	public void setHashTripa(String hashTripa) {
		this.hashTripa = hashTripa;
	}

	@Column(name = "HASH_INCREMENTO")
	public Integer getHashIncremento() {
		return this.hashIncremento;
	}

	public void setHashIncremento(Integer hashIncremento) {
		this.hashIncremento = hashIncremento;
	}

	@Column(name = "ICMS_ISENTO", precision = 18, scale = 6)
	public BigDecimal getIcmsIsento() {
		return this.icmsIsento;
	}

	public void setIcmsIsento(BigDecimal icmsIsento) {
		this.icmsIsento = icmsIsento;
	}

	@Column(name = "ICMS_SUBSTITUICAO", precision = 18, scale = 6)
	public BigDecimal getIcmsSubstituicao() {
		return this.icmsSubstituicao;
	}

	public void setIcmsSubstituicao(BigDecimal icmsSubstituicao) {
		this.icmsSubstituicao = icmsSubstituicao;
	}

	@Column(name = "ICMS_NAO_TRIBUTADO", precision = 18, scale = 6)
	public BigDecimal getIcmsNaoTributado() {
		return this.icmsNaoTributado;
	}

	public void setIcmsNaoTributado(BigDecimal icmsNaoTributado) {
		this.icmsNaoTributado = icmsNaoTributado;
	}

	@Column(name = "NUMERO_NOTA_MANUAL", length = 8)
	public String getNumeroNotaManual() {
		return this.numeroNotaManual;
	}

	public void setNumeroNotaManual(String numeroNotaManual) {
		this.numeroNotaManual = numeroNotaManual;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_SINCRONIZACAO", length = 10)
	public Date getDataSincronizacao() {
		return this.dataSincronizacao;
	}

	public void setDataSincronizacao(Date dataSincronizacao) {
		this.dataSincronizacao = dataSincronizacao;
	}

	@Column(name = "HORA_SINCRONIZACAO", length = 8)
	public String getHoraSincronizacao() {
		return this.horaSincronizacao;
	}

	public void setHoraSincronizacao(String horaSincronizacao) {
		this.horaSincronizacao = horaSincronizacao;
	}

	@Column(name = "EXPORTADO", length = 1)
	public String getExportado() {
		return this.exportado;
	}

	public void setExportado(String exportado) {
		this.exportado = exportado;
	}
}
